destination: /zone/home/project/mango_ingest
do_dry_run: false
filter_func: null
filter_func_kwargs: null
glob:
- '*.py'
- '*.json'
ignore: []
ignore_glob: []
metadata_handler: null
metadata_handler_kwargs: null
metadata_mtime: false
metadata_path: []
no_watch: false
observer: native
path: .
recursive: false
regex: []
restart: null
sync: false
verbose: 1
verify_checksum: false
