destination: /zone/home/project/ingest
do_dry_run: false
filter_func: null
filter_func_kwargs: null
glob:
- '*.py'
- '*.md'
ignore: []
ignore_glob: []
no_watch: false
observer: native
path: .
path_extract: []
recursive: true
regex: []
restart: null
sync: true
verbose: true
verify_checksum: false
